server:
  port: 8888

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
spring:
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
  datasource:
    url: jdbc:mysql://localhost:3306/politics?useSSL=false
    username: root
    password: password

logging:
  level:
    org.hibernate: DEBUG
    com.msa.jrg.family_planning.familyService.resources: DEBUG

address:
  defaultCountry: United States